version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CACHE_BUSTER: 2
    container_name: portfolio
    ports:
      - "3000:3000"
    restart: unless-stopped