version: '3.8'

services:
  portfolio:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./content:/app/content
    ports:
      - "3000:3000"
    networks:
      - portfolio-network
    restart: unless-stopped

networks:
  portfolio-network:
    driver: bridge