services:
  portfolio-v2:
    image: ghcr.io/kingelvyn/portfolio:v2-c2623d3
    container_name: portfolio-v2
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}