name: CI

on:
  push:
    branches:
      - main
      - v1
  pull_request:

jobs:
  build-and-test:
    if: ${{ github.event_name == 'pull_request' || !contains(github.event.head_commit.message, 'Deploy ') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Download dependencies
        run: go mod download

      - name: Build application
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...